project_name: scs-demo-binary

before:
  hooks:
    - go mod tidy

builds:
  - binary: scs-demo-binary-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source_code'

sboms:
  - artifacts: source
    cmd: syft
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

signs:
  - artifacts: checksum
    certificate: '${artifact}.pem'
    cmd: cosign
    args:
      - sign-blob
      - "--yes"
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    output: true
