name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      
      - name: Set up Syft
        uses: anchore/sbom-action/download-syft@v0
      
      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
